### ISSUE TITLE
PreTeXtual not showing up in "Install Packages"

### ISSUE THREAD

**Issue by aluminum1** [daverosoff/MBXTools#42]
PreTeXtual doesn't show up under "Install Packages" on my (recent) version of Sublime Text, version 3.2.1.

Kind regards
Bruce Bartlett

**Comment by daverosoff** [comment]
Thanks for the message. I will look into it. What OS are you running, and which Sublime build number?

**Comment by daverosoff** [comment]
I'm still unable to reproduce this error. Closing the issue for now.
